/*
 * Name:  Adam Clements
 * Date Submitted: 9/21/2022
 * Lab Section: 2121-002
 * Assignment Name: Infix to Postfix Conversion
 */

#include <iostream>
#include <string>
#include <stack>

using namespace std;

//Converts an infix arithmetic expression into postfix
//The function takes 3 parameters
//First parameter: array of strings for infix expression
//    each string is either an integer number or operator symbol
//Second parameter: number of strings in infix expression
//Third parameter: array of strings for postfix expression
//    generated by function, same format as first parameter
//    assumes that postfix is at least the size of postfix
//Return value: int, number of strings in postfix expression
//    Returns 0 if an error is encountered when converting expression
//    An error occurs with a mismatched parenthesis, e.g. ( ( ) or ( ) ) etc.
//Operator symbols:
// ( : left parenthesis, all operations between this and ")" take place first
// ) : right parenthesis, all op.s back to previous "(" take place first
// * : multiplication, higher precedence - takes place before "+" and "-"
// / : division, higher precedence - takes place before "+" and "-"
// % : remainder, higher precedence - takes place before "+" and "-"
// + : addition, lower precedence - takes place after "*" , "/" , "%"
// - : subtraction, lower precedence - takes place after "*" , "/" , "%"
//The function is not specified to work with any other operator symbols
//Any string in infix may be assumed to be an integer operand if none
// of the above symbols

//Function to return a "precedence value" for a given operator for simple comparison checks when popping the stack
//(this will also check the precedence of parenthesis which I give a value of 0 by default so the operator is pushed)
int precedence(std::string str){
	if(str == "*" || str == "/" || str == "%"){
		return 2;
	}
	else if(str == "+" || str == "-"){
		return 1;
	}
	else{
		return 0;
	}
}

//reorder the infix expression as a properly formatted postfix expression, and return the length of postfix
int infixToPostfix(string infix[], int length, string postfix[]){
	//variables used later (stack for operators, currentPos for filling postfix)
	stack<std::string> temp;
	int currentPos = 0;
	//iterate through the input expression
	for(int i=0;i<length;i++){
		//if the current char is a number, send it to postfix
		if(infix[i] >= "0" && infix[i] <= "9"){
			postfix[currentPos++] = infix[i];
		}
		//if the current char is a parenthesis, send it to the stack
		else if(infix[i] == "("){
			temp.push(infix[i]);
		}
		//if the program encounters a ")" unload the stack until it finds the previous "("
		else if(infix[i] == ")"){
			while(!temp.empty() && temp.top() != "("){
				postfix[currentPos++] = temp.top();
				temp.pop();
			}
			//if the code has full emptied the stack, not finding "(", return 0
			if(temp.empty()){
				return 0;
			}
			else{
				//pop the "(" from the stack
				temp.pop();
			}
		}
		//if the current char is an operator, assign it a precedence value to make comparison easy
		//("*","/","%" = 2, "+","-" = 2), and check the operator stack
		else if(infix[i] == "*" || infix[i] == "/" || infix[i] == "%" || infix[i] == "+" || infix[i] == "-"){
			//pop all of the operators from the stack that have a greater than or equal precedence value,
			//unless a parenthetical is found in the stack in which case, push the current operator
			while(!temp.empty() && precedence(infix[i]) <= precedence(temp.top())){
				postfix[currentPos++] = temp.top();
				temp.pop();
			}
			temp.push(infix[i]);
		}
	}
	//empty the rest of the stack to postfix
	while(!temp.empty()){
		//if there is a remaining "(" then there was no matching ")" anywhere in the infix
		if(temp.top() == "("){
			return 0;
		}
		postfix[currentPos++] = temp.top();
		temp.pop();
	}
	//return the new length of postfix
	return currentPos;
}